export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

import './globals.css';

import fonts from './fonts';

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={fonts}>{children}</body>
        </html>
    );
}
