export enum Title {
  PRODUCT = 'PRODUKT',
  DESCRIPTION = 'OPIS',
  PRICE = 'CENA',
  QUANTITY = 'ILOŚĆ',
  VISIBLE = 'WIDOCZNY',
  CATEGORY = 'KATEGORIA',
  PRICE_HISTORY = 'HISTORIA CEN',
  PHOTOS = 'ZDJĘCIA',
  ACTION = 'AKCJE'
}
